language: go

go:
  - "1.11.x"

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

env:
  global:
    - GOLANGCI_LINT_VERSION=1.15.0
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION}

before_script:
  - psql -c "CREATE DATABASE reserve_data;" -U postgres
  - psql -c "CREATE USER reserve_data WITH PASSWORD 'reserve_data';" -U postgres
  - psql -c "ALTER ROLE reserve_data SUPERUSER;" -U postgres

script:
  - golangci-lint run --config .golangci.yml ./...
  - go test -v -race ./...

after_success:
  - docker --version
  - docker build -f Dockerfile.next -t kybernetwork/reserve-data:$TRAVIS_COMMIT .

deploy:
  provider: script
  script: bash .travis/docker_push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^v3-develop|develop|staging|master$
