go_import_path: github.com/KyberNetwork/reserve-data

language: go

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get github.com/mattn/goveralls

script:
  - gometalinter --config=gometalinter.json ./...
  - pushd common && gometalinter --vendor --disable-all --enable=vetshadow ./...; popd
  - pushd cmd && gometalinter --vendor --disable-all --enable=vetshadow ./...; popd
  - pushd exchange && gometalinter --vendor --disable-all --enable=vetshadow ./...; popd
  - $GOPATH/bin/goveralls -v -service=travis-ci

go:
  - "1.10.x"
