language: go

go:
  - "1.11.x"

services:
  - docker

env:
  global:
    - GOMETALINTER_VERSION=2.0.11
    - GO111MODULE=on
    - PATH=$PATH:${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

install:
  - ./.travis/gometalinter-install.sh
  - export PATH=$PATH:${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

cache:
  directories:
    - ${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

script:
  - GO111MODULE=off gometalinter --config=gometalinter.json ./...
  - go test -v -race -mode vendor ./...

after_success:
  - docker --version
  - docker build -f Dockerfile.next -t kybernetwork/reserve-data:$TRAVIS_COMMIT .

deploy:
  provider: script
  script: bash .travis/docker_push
  on:
    all_branches: true
